version: '3.4'

services:
  webapi.api:
    image: ${DOCKER_REGISTRY-}elitedemowebapiapi
    build:
      context: .
      dockerfile: src/WebAPI/WebAPI.API/Dockerfile
    env_file:
      - config/.env
    depends_on:
      - webapi.db
    networks:
      - elitedemo-net

  webapi.db:
    image: "mcr.microsoft.com/mssql/server"
    env_file:
      - config/.env
    expose:
      - '1433'
    networks:
      - elitedemo-net

  portal.spa:
    image: ${DOCKER_REGISTRY-}elitedemoportalspa
    build:
      context: .
      dockerfile: src/Portal/Portal.UI/Dockerfile
    env_file:
      - config/.env
    ports:
      - '80:80'
    depends_on:
      - webapi.api
    networks:
      - elitedemo-net

networks:
  elitedemo-net:
