//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v1.3.0.4
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebAPI.Infrastructure.Entities
{
   public partial class ShiftSettings: global::WebAPI.Infrastructure.Entities.BaseEntity
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected ShiftSettings(): base()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="rule"></param>
      /// <param name="quantity"></param>
      /// <param name="shoplocation"></param>
      public ShiftSettings(string rule, byte quantity, global::WebAPI.Infrastructure.Entities.ShopLocations shoplocation)
      {
         if (string.IsNullOrEmpty(rule)) throw new ArgumentNullException(nameof(rule));
         this.Rule = rule;
         this.Quantity = quantity;
         if (shoplocation == null) throw new ArgumentNullException(nameof(shoplocation));
         this.ShopLocation = shoplocation;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="rule"></param>
      /// <param name="quantity"></param>
      /// <param name="shoplocation"></param>
      public static ShiftSettings Create(string rule, byte quantity, global::WebAPI.Infrastructure.Entities.ShopLocations shoplocation)
      {
         return new ShiftSettings(rule, quantity, shoplocation);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Rule { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public byte Quantity { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::WebAPI.Infrastructure.Entities.ShopLocations ShopLocation { get; set; }

   }
}

