//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v1.3.0.4
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace WebAPI.Infrastructure.Entities
{
   public partial class ShopLocations: global::WebAPI.Infrastructure.Entities.BaseEntity
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected ShopLocations(): base()
      {
         ShiftBookings = new System.Collections.Generic.HashSet<global::WebAPI.Infrastructure.Entities.ShiftBookings>();
         ShiftSettings = new System.Collections.Generic.HashSet<global::WebAPI.Infrastructure.Entities.ShiftSettings>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="name"></param>
      /// <param name="shop"></param>
      public ShopLocations(string name, global::WebAPI.Infrastructure.Entities.Shops shop)
      {
         if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
         this.Name = name;
         if (shop == null) throw new ArgumentNullException(nameof(shop));
         this.Shop = shop;

         this.ShiftBookings = new System.Collections.Generic.HashSet<global::WebAPI.Infrastructure.Entities.ShiftBookings>();
         this.ShiftSettings = new System.Collections.Generic.HashSet<global::WebAPI.Infrastructure.Entities.ShiftSettings>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="name"></param>
      /// <param name="shop"></param>
      public static ShopLocations Create(string name, global::WebAPI.Infrastructure.Entities.Shops shop)
      {
         return new ShopLocations(name, shop);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Name { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

      public virtual ICollection<global::WebAPI.Infrastructure.Entities.ShiftBookings> ShiftBookings { get; private set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::WebAPI.Infrastructure.Entities.Shops Shop { get; set; }

      public virtual ICollection<global::WebAPI.Infrastructure.Entities.ShiftSettings> ShiftSettings { get; private set; }

   }
}

